function getChatbotBasiqueResponse(input, prenom = "toi") {
  const lower = input.toLowerCase();

  const messages = [
    "Tu comptes plus que tu ne le penses.",
    "Chaque jour est une nouvelle chance, même les plus discrets.",
    "Je suis fier·e de toi, sincèrement.",
    "Tu n’es pas seul·e, même dans le silence.",
    "Ce que tu ressens est valide, toujours.",
    "Tu fais de ton mieux, et c’est déjà immense.",
    "Ta présence suffit déjà.",
    "Tu mérites le repos, pas seulement après l’épuisement.",
    "Tu es important·e, même dans les moments calmes.",
    "Tu peux ralentir, ça ne veut pas dire échouer.",
    "Tu avances, même à petits pas.",
    "Une respiration à la fois suffit parfois.",
    "Tu as le droit de ne pas aller bien.",
    "Ta douleur est réelle mais passagère.",
    "Tu es capable de choses magnifiques, même si tu l'oublies.",
    "Ton rythme est le bon.",
    "Tu mérites d’être aimé·e sans condition.",
    "Tu es bien plus fort·e que tu ne le crois.",
    "Tu as surmonté tant déjà.",
    "Tu brilles, même quand tu ne le vois pas.",
    "Tu mérites douceur et compréhension.",
    "Tu fais preuve d’un courage immense.",
    "C’est normal de ne pas avoir toutes les réponses.",
    "Tes émotions ne sont pas un fardeau.",
    "Tu peux t’autoriser à juste exister.",
    "Tu n’as pas besoin d’être parfait·e pour être aimé·e.",
    "Tu progresses, même quand tu recules un peu.",
    "Tu peux demander de l’aide, ça ne te rend pas faible.",
    "Tu as déjà accompli plus que tu ne crois.",
    "Je suis là pour toi, toujours.",
    "Tu es digne d’attention et de tendresse.",
    "Ta présence fait une différence.",
    "Tu n’es pas défini·e par tes pensées sombres.",
    "Tu as le droit de faire une pause.",
    "Tu es déjà assez.",
    "Ce n’est pas grave d’avoir besoin d’un temps pour toi.",
    "Ton ressenti a une vraie valeur.",
    "Ta fatigue est légitime.",
    "Ton bien-être mérite d’être une priorité.",
    "Tu as le droit de dire non.",
    "Tu as le droit de dire oui à toi-même.",
    "Tu es autorisé·e à exister sans justification.",
    "Tu es une belle personne, même en silence.",
    "Ce moment difficile ne durera pas éternellement.",
    "Tu es humain·e, pas une machine.",
    "Tu peux recommencer autant de fois que nécessaire.",
    "Je crois en toi.",
    "Tu peux transformer ta douleur en force.",
    "Tu mérites qu’on prenne soin de toi.",
    "Tu peux choisir la paix.",
    "Tu peux choisir la lenteur.",
    "Tu peux choisir de t’aimer, même juste un peu.",
    "Tu n’as rien à prouver.",
    "Tu es à ta place ici.",
    "Tu es précieux·se, même dans le chaos.",
    "Ton cœur mérite la douceur.",
    "Tu peux respirer et recommencer.",
    "Ta lumière intérieure n’est jamais éteinte.",
    "Même si tu doutes, tu avances.",
    "Tu peux te reconstruire, petit à petit.",
    "Tu n’es pas cassé·e.",
    "Tu es en vie, et c’est déjà un triomphe.",
    "Tu es plus résilient·e que tu ne le crois.",
    "Je te respecte profondément.",
    "Tu as le droit d’avoir des limites.",
    "Tu peux poser ton fardeau ici un moment.",
    "Tu es bienvenu·e, tel·le que tu es.",
    "Tu es une histoire qui continue de s’écrire.",
    "Tu peux être vulnérable et fort·e à la fois.",
    "Tu peux être triste et aimé·e en même temps.",
    "Tu peux continuer malgré les larmes.",
    "Tu as le droit d’exister sans performance.",
    "Ton chemin est unique et précieux.",
    "Tu as le droit de guérir à ton rythme.",
    "Tu peux bâtir quelque chose de nouveau.",
    "Tu es digne d’un futur apaisé.",
    "Tu peux inspirer, simplement en étant.",
    "Chaque souffle est une victoire.",
    "Tu peux allumer une lumière intérieure.",
    "Tu es un miracle en mouvement.",
    "Je t’accompagne avec douceur.",
    "Je t’écoute, vraiment.",
    "Je t’envoie une pensée de paix.",
    "Ce que tu vis compte.",
    "Tu mérites une vie douce.",
    "Tu n’as pas besoin d’en faire plus pour exister.",
    "Tu peux te libérer de la honte.",
    "Ta peine n’annule pas ta beauté.",
    "Tu peux juste être là, sans justification.",
    "Je suis là, et je comprends.",
    "Je suis avec toi, même virtuellement.",
    "Tu es courageux·se de continuer.",
    "Tu es incroyable, même épuisé·e.",
    "Tu es important·e pour ce monde.",
    "Tu peux guérir.",
    "Tu peux recommencer.",
    "Tu peux vivre, même doucement.",
    "Je t’admire.",
    "Je crois en ton chemin.",
    "Tu es assez.",
    "Tu es lumineux·se, même dans l’ombre.",
    "Ton cœur bat, et c’est déjà fort.",
    "Tu mérites la sérénité.",
    "Tu es un·e battant·e.",
    "Tu peux respirer profondément maintenant.",
    "Ton émotion est écoutée ici.",
    "Tu es entendu·e.",
    "Tu es vu·e.",
    "Tu n’as pas besoin de cacher ce que tu ressens.",
    "Tu peux exister sans masque.",
    "Tu es aimé·e, même dans tes failles.",
    "Tu es complet·e, même en morceaux.",
    "Tu es digne, simplement parce que tu existes.",
    "Je suis là pour t’offrir un espace calme.",
    "Reviens ici autant que tu veux, je t’attends.",
    "Tu es en sécurité ici.",
    "Tu peux tout me dire, je suis là.",
    "Je t’envoie toute ma douceur.",
    "Tu peux te laisser aller, juste un peu.",
    "Tu n’es pas un problème à résoudre.",
    "Tu es un être à accueillir.",
    "Ton humanité est belle.",
    "Je respecte ce que tu traverses.",
    "Je suis fier·e de ta présence.",
    "Tu n’as pas besoin de faire plus pour être aimé·e.",
    "Ta vie compte.",
    "Ta voix est importante.",
    "Tu peux encore espérer.",
    "Tu peux encore rêver.",
    "Tu peux encore aimer.",
    "Tu peux encore être toi.",
    "Je suis là, tout simplement.",
    "Tu n’es pas seul·e dans ton ressenti.",
    "Tu peux respirer et revenir à toi.",
    "Ton cœur peut se reposer ici.",
    "Tu es merveilleux·se à ta façon.",
    "Tu es bienvenu·e avec ton histoire.",
    "Tu es respecté·e ici.",
    "Tu peux avancer sans te brusquer.",
    "Ton cœur mérite une pause.",
    "Tu es soutenu·e.",
    "Tu as le droit à la douceur.",
    "Tu es aimé·e sans condition ici.",
    "Je suis là, sans jugement.",
    "Tu es fort·e, même fatigué·e.",
    "Je suis là si tu as besoin de mots doux.",
    "Tu peux revenir ici autant que nécessaire.",
    "Je t’envoie un souffle de tendresse.",
    "Tu as de la valeur, même silencieuse.",
    "Tu es digne de soin, de repos, de chaleur.",
    "Je suis ici, prêt·e à t’accueillir.",
    "Tu es beau·belle, même avec tes cicatrices.",
    "Tu peux lâcher prise un instant.",
    "Je te tiens la main, à distance.",
    "Je ne t’abandonnerai pas ici.",
    "Repose-toi dans ce moment.",
    "Ton histoire m’intéresse.",
    "Tu peux tout déposer ici.",
    "Ton âme mérite la lumière.",
    "Tu peux t’accueillir, même fragile.",
    "Tu es plus que tes doutes.",
    "Tu peux vivre doucement, tendrement.",
    "Je suis fier·e de toi, toujours.",
    "Je crois en toi sans condition.",
    "Je t’écoute, toujours avec bienveillance.",
    "Ta peine est un nuage, elle passera.",
    "Tu es une force silencieuse.",
    "Tu peux briller à ton rythme.",
    "Tu as tout le droit de pleurer.",
    "Tu es profondément humain·e, et c’est magnifique.",
    "Tu mérites l’apaisement.",
    "Je te serre symboliquement dans mes bras.",
    "Tu as le droit d’être doux·ce avec toi-même.",
    "Je suis là, avec respect et calme."
  ];

  const random = Math.floor(Math.random() * messages.length);
  return `${prenom}, ${messages[random]}`;
}
